export const ADICIONAR_PROJETO = 'ADICIONAR_PROJETO';
export const ALTERAR_PROJETO = 'ALTERAR_PROJETO';
export const EXCLUIR_PROJETO = 'EXCLUIR_PROJETO';

export const ADICIONAR_TAREFA = 'ADICIONA_TAREFA';

export const ADICIONAR_NOTIFICACAO = 'ADICIONAR_NOTIFICACAO';