export const ADICIONAR_PROJETO = 'ADICIONAR_PROJETO';
export const ALTERAR_PROJETO = 'ALTERAR_PROJETO';
export const EXCLUIR_PROJETO = 'EXCLUIR_PROJETO';
export const DEFINIR_PROJETOS = 'DEFINIR_PROJETOS';

export const ADICIONAR_TAREFA = 'ADICIONA_TAREFA';
export const DEFINIR_TAREFAS = 'DEFINIR_TAREFAS';
export const ALTERAR_TAREFA = 'ALTERAR_TAREFA';

export const ADICIONAR_NOTIFICACAO = 'ADICIONAR_NOTIFICACAO';